version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "gradle"
    directory: "/"
    target-branch: "4.4.x"
    schedule:
      interval: "daily"
  - package-ecosystem: "gradle"
    directory: "/"
    target-branch: "4.3.x"
    schedule:
      interval: "daily"
  - package-ecosystem: "gradle"
    directory: "/"
    target-branch: "4.1.x"
    schedule:
      interval: "daily"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
